# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import TypedDict
from typed_aster.core import TimestampMillis
from typed_aster.core.endpoint.rpc import RpcEndpoint


class OpenInterest(TypedDict):
  """Open interest of one symbol."""

  symbol: str
  """Symbol, e.g. `BTCUSDT`."""
  openInterest: Decimal
  """Open interest, in base units."""
  time: TimestampMillis
  """Data time."""


class Request(TypedDict):
  symbol: str
  """Symbol, e.g. `BTCUSDT`."""


class OpenInterestEndpoint(RpcEndpoint):
  """Current open interest of one perpetual, in base units."""

  async def open_interest(
    self, symbol: str, *, validate: bool | None = None
  ) -> OpenInterest:
    """Current open interest of one perpetual, in base units.

    Args:
      symbol: Symbol, e.g. `BTCUSDT`.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
    """
    return await self.request(
      Request(symbol=symbol),
      method='GET',
      path='openInterest',
      meta={'sign': 'none'},
      validate=validate,
      request_type=Request,
      response_type=OpenInterest,
    )
