# Generated by typed-dev — see CONTRIBUTING.md.
from betterproto2.grpclib.grpclib_client import MetadataLike
from typed_core.grpc import GrpcEndpoint, server_stream
from typed_core.util.streams import StreamManager
from typed_dydx.protos.dydxprotocol.clob import (
  StreamOrderbookUpdatesRequest,
  StreamOrderbookUpdatesResponse,
)
from typed_dydx.protos.dydxprotocol.subaccounts import SubaccountId


class StreamOrderbookUpdates(GrpcEndpoint):
  """Stream a full node's orderbook updates, fills, taker orders, subaccount updates, and price updates.

  Served only by a full node started with `--grpc-streaming-enabled`, never by the public gRPC providers: build the `Chain` client against your own node (plaintext gRPC, port 9090 by default) to call it.

  Like every stream, it returns a `StreamManager`: use `async with client.chain.clob.stream_orderbook_updates(clob_pair_id=[0]) as stream:` (unsubscribed on exit), or `stream = await ...` and `await stream.unsubscribe()` when done. Opening it waits for the node's response headers, so a request the node rejects, an unreachable node (`NetworkError`), or a node without streaming enabled raises there rather than mid-iteration. The node reports an invalid request (for example, all three id lists empty) with gRPC status `UNKNOWN`, so it raises `ApiError`. `stream.reply` is `None`.

  Each response the stream yields is one batch the node flushed at once. Its `updates` are `StreamUpdate`s, each carrying exactly one of `orderbook_update`, `order_fill`, `taker_order`, `subaccount_update`, or `price_update`, plus `block_height` (updates carry no block time) and `exec_mode`, the Cosmos SDK execution mode the node was in when it produced the update:

  - `7` (`ExecModeFinalize`): finalized. Everything staged during `FinalizeBlock` is sent as one batch once the block commits.
  - Below `7` (`CheckTx`, `ReCheckTx`, `PrepareProposal`, ...): optimistic. Each node matches against its own local orderbook, so these may later be reverted, replayed, or name a different maker order than the block finalizes.
  - `102` (dYdX's `ExecModePrepareCheckState`): the post-commit stage in which the node rebuilds its orderbook. The initial snapshots are sent with it, and fills and book changes it replays there are optimistic too.

  The first orderbook update of a subscription is a snapshot (`orderbook_update.snapshot`): discard local book state when one arrives.

  A `StreamOrderbookFill` carries a `clob_match` (exactly one of `match_orders`, `match_perpetual_liquidation`, or `match_perpetual_deleveraging`), the `orders` involved, and `fill_amounts`: for each order in `orders`, its total filled base quantums after this match (cumulative, not this match's amount). Deleveraging fills involve no orders, so they carry no `orders`, `fill_amounts`, or price.

  `clob_pair_id` selects the CLOB pairs to stream orderbook updates and fills for (left empty, the node streams every pair), `subaccount_ids` the subaccounts to stream subaccount updates for, and `market_ids` the oracle markets to stream prices for; at least one of the three must be non-empty or the node rejects the request. `filter_orders_by_subaccount_id` restricts orderbook updates, fills, and taker orders to `subaccount_ids` (which must then be non-empty). Unpatched v9.7.1 nodes crash on a liquidation taker order while filtering (https://github.com/dydxprotocol/v4-chain/issues/3414): only enable it against a node running the fix.

  The stream can end without an error when the node drops the subscription, for example a reader too slow for the node's buffer; resubscribe to keep listening."""

  def stream_orderbook_updates(
    self,
    *,
    clob_pair_id: list[int] | None = None,
    subaccount_ids: list[SubaccountId] | None = None,
    market_ids: list[int] | None = None,
    filter_orders_by_subaccount_id: bool | None = None,
    metadata: MetadataLike | None = None,
  ) -> StreamManager[StreamOrderbookUpdatesResponse, None, None]:
    """Stream a full node's orderbook updates, fills, taker orders, subaccount updates, and price updates.

    Served only by a full node started with `--grpc-streaming-enabled`, never by the public gRPC providers: build the `Chain` client against your own node (plaintext gRPC, port 9090 by default) to call it.

    Like every stream, it returns a `StreamManager`: use `async with client.chain.clob.stream_orderbook_updates(clob_pair_id=[0]) as stream:` (unsubscribed on exit), or `stream = await ...` and `await stream.unsubscribe()` when done. Opening it waits for the node's response headers, so a request the node rejects, an unreachable node (`NetworkError`), or a node without streaming enabled raises there rather than mid-iteration. The node reports an invalid request (for example, all three id lists empty) with gRPC status `UNKNOWN`, so it raises `ApiError`. `stream.reply` is `None`.

    Each response the stream yields is one batch the node flushed at once. Its `updates` are `StreamUpdate`s, each carrying exactly one of `orderbook_update`, `order_fill`, `taker_order`, `subaccount_update`, or `price_update`, plus `block_height` (updates carry no block time) and `exec_mode`, the Cosmos SDK execution mode the node was in when it produced the update:

    - `7` (`ExecModeFinalize`): finalized. Everything staged during `FinalizeBlock` is sent as one batch once the block commits.
    - Below `7` (`CheckTx`, `ReCheckTx`, `PrepareProposal`, ...): optimistic. Each node matches against its own local orderbook, so these may later be reverted, replayed, or name a different maker order than the block finalizes.
    - `102` (dYdX's `ExecModePrepareCheckState`): the post-commit stage in which the node rebuilds its orderbook. The initial snapshots are sent with it, and fills and book changes it replays there are optimistic too.

    The first orderbook update of a subscription is a snapshot (`orderbook_update.snapshot`): discard local book state when one arrives.

    A `StreamOrderbookFill` carries a `clob_match` (exactly one of `match_orders`, `match_perpetual_liquidation`, or `match_perpetual_deleveraging`), the `orders` involved, and `fill_amounts`: for each order in `orders`, its total filled base quantums after this match (cumulative, not this match's amount). Deleveraging fills involve no orders, so they carry no `orders`, `fill_amounts`, or price.

    `clob_pair_id` selects the CLOB pairs to stream orderbook updates and fills for (left empty, the node streams every pair), `subaccount_ids` the subaccounts to stream subaccount updates for, and `market_ids` the oracle markets to stream prices for; at least one of the three must be non-empty or the node rejects the request. `filter_orders_by_subaccount_id` restricts orderbook updates, fills, and taker orders to `subaccount_ids` (which must then be non-empty). Unpatched v9.7.1 nodes crash on a liquidation taker order while filtering (https://github.com/dydxprotocol/v4-chain/issues/3414): only enable it against a node running the fix.

    The stream can end without an error when the node drops the subscription, for example a reader too slow for the node's buffer; resubscribe to keep listening.

    Args:
      metadata: gRPC metadata forwarded to the call.

    References:
      - [Official docs](https://docs.dydx.xyz/nodes/full-node-streaming)
    """
    return server_stream(
      self.channel,
      '/dydxprotocol.clob.Query/StreamOrderbookUpdates',
      StreamOrderbookUpdatesRequest(
        clob_pair_id=(clob_pair_id if clob_pair_id is not None else []),
        subaccount_ids=(subaccount_ids if subaccount_ids is not None else []),
        market_ids=(market_ids if market_ids is not None else []),
        filter_orders_by_subaccount_id=(
          filter_orders_by_subaccount_id
          if filter_orders_by_subaccount_id is not None
          else False
        ),
      ),
      StreamOrderbookUpdatesResponse,
      metadata=metadata,
    )
