# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.decimals import PlainDecimal
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint
from typed_bitget.schemas import (
  MixMarginMode,
  MixOrderSide,
  MixProductType,
  MixReduceOnly,
  MixStpMode,
  MixTimeInForce,
  MixTradeSideRequest,
)


class MixOrderResult(TypedDict):
  """Identifiers of the order just acted on."""

  orderId: str
  """Order ID assigned by the venue."""
  clientOid: str
  """Client-supplied order ID, echoed back."""


class MixLimitOrderRequest(TypedDict):
  """A futures limit order to place."""

  symbol: str
  """Futures symbol, e.g. "BTCUSDT"."""
  productType: MixProductType
  marginMode: MixMarginMode
  marginCoin: str
  """Margin coin, e.g. "USDT"."""
  size: PlainDecimal | str
  """Order size, in base coin."""
  price: PlainDecimal | str
  """Limit price. Required for a limit order; omit for a market order."""
  side: MixOrderSide
  orderType: Literal['limit']
  """Order type."""
  tradeSide: NotRequired[MixTradeSideRequest]
  force: NotRequired[MixTimeInForce]
  clientOid: NotRequired[str]
  """Caller-supplied order ID, echoed back on responses. Must be unique among the account's open orders."""
  reduceOnly: NotRequired[MixReduceOnly]
  presetStopSurplusPrice: NotRequired[PlainDecimal | str]
  """Take-profit trigger price to attach to the position this order opens."""
  presetStopLossPrice: NotRequired[PlainDecimal | str]
  """Stop-loss trigger price to attach to the position this order opens."""
  stpMode: NotRequired[MixStpMode]


class MixMarketOrderRequest(TypedDict):
  """A futures market order to place."""

  symbol: str
  """Futures symbol, e.g. "BTCUSDT"."""
  productType: MixProductType
  marginMode: MixMarginMode
  marginCoin: str
  """Margin coin, e.g. "USDT"."""
  size: PlainDecimal | str
  """Order size, in base coin."""
  side: MixOrderSide
  orderType: Literal['market']
  """Order type."""
  tradeSide: NotRequired[MixTradeSideRequest]
  force: NotRequired[MixTimeInForce]
  clientOid: NotRequired[str]
  """Caller-supplied order ID, echoed back on responses. Must be unique among the account's open orders."""
  reduceOnly: NotRequired[MixReduceOnly]
  presetStopSurplusPrice: NotRequired[PlainDecimal | str]
  """Take-profit trigger price to attach to the position this order opens."""
  presetStopLossPrice: NotRequired[PlainDecimal | str]
  """Stop-loss trigger price to attach to the position this order opens."""
  stpMode: NotRequired[MixStpMode]


Request = MixLimitOrderRequest | MixMarketOrderRequest


class Place(RpcEndpoint):
  """Place a futures order, private."""

  async def place(
    self,
    mix_order_request: Request,
    *,
    validate: bool | None = None,
  ) -> MixOrderResult:
    """Place a futures order, private.

    Args:
      mix_order_request: New order request.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-contract-trade/classic-contract-trade#place-order)
    """
    return await self.request(
      mix_order_request,
      method='POST',
      path='/api/v2/mix/order/place-order',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=MixOrderResult,
    )
