# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.decimals import PlainDecimal
from typing_extensions import TypedDict
from typed_aster.core.endpoint.rpc import RpcEndpoint
from typed_aster.schemas import Withdrawal


class Request(TypedDict):
  asset: str
  """Asset name, e.g. `USDT`."""
  chainId: int
  """Target chain id (`101`, Solana)."""
  amount: PlainDecimal | str
  """Withdrawal amount."""
  fee: PlainDecimal | str
  """Withdrawal fee (see `wallet.estimate_withdraw_fee`)."""
  receiver: str
  """Recipient Solana address."""


class SolanaWithdraw(RpcEndpoint):
  """Withdraw from the spot account to a Solana address."""

  async def solana_withdraw(
    self,
    *,
    asset: str,
    chain_id: int,
    amount: PlainDecimal | str,
    fee: PlainDecimal | str,
    receiver: str,
    validate: bool | None = None,
  ) -> Withdrawal:
    """Withdraw from the spot account to a Solana address.

    Args:
      asset: Asset name, e.g. `USDT`.
      chain_id: Target chain id (`101`, Solana).
      amount: Withdrawal amount.
      fee: Withdrawal fee (see `wallet.estimate_withdraw_fee`).
      receiver: Recipient Solana address.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://asterdex.github.io/aster-api-website/aster-chain/endpoints/#user-solana-withdraw-withdraw_1)
    """
    return await self.request(
      Request(asset=asset, chainId=chain_id, amount=amount, fee=fee, receiver=receiver),
      method='POST',
      path='spot/user-solana-withdraw',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=Withdrawal,
    )
