# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, NotRequired, TypedDict
from typed_lighter.core.endpoint.stream import StreamEndpoint
from typed_lighter.schemas import (
  AccountAsset,
  AccountPosition,
  Order,
  PositionFunding,
  Trade,
)


class EmptyAccountPosition(TypedDict):
  """An uninitialized account-market position with sign zero and unset decimal fields."""

  market_id: int
  """Market id."""
  symbol: str
  """Market symbol."""
  initial_margin_fraction: Decimal | Literal['']
  """Initial margin fraction set for this market, in percent (`5.00` = 20x leverage). May be empty when unset."""
  open_order_count: int
  """Open orders in this market."""
  pending_order_count: int
  """Untriggered conditional orders in this market."""
  position_tied_order_count: int
  """Orders tied to the position (reduce-only stop-loss/take-profit)."""
  sign: Literal[0]
  """Zero for an uninitialized position."""
  position: Decimal
  """Position size, in base units (unsigned; see `sign`)."""
  avg_entry_price: Decimal | Literal['']
  """Average entry price. May be empty when unset."""
  position_value: Decimal | Literal['']
  """Position value at the mark price. May be empty when unset."""
  unrealized_pnl: Decimal | Literal['']
  """Unrealized PnL. May be empty when unset."""
  realized_pnl: Decimal | Literal['']
  """Realized PnL. May be empty when unset."""
  liquidation_price: Decimal | Literal['']
  """Estimated liquidation price; `0` when none. May be empty when unset."""
  total_funding_paid_out: NotRequired[Decimal]
  """Cumulative funding paid out on this position; absent on markets the account never held."""
  margin_mode: Literal[0, 1]
  """`0` cross margin, `1` isolated margin (lighter-go's position margin modes `CrossMargin`/`IsolatedMargin`)."""
  margin_set_flag: int
  """Whether leverage/margin settings were set for this market (`1`), meaning it was traded at least once."""
  allocated_margin: Decimal | Literal['']
  """Isolated margin allocated to the position (`0` in cross mode). May be empty when unset."""
  total_discount: NotRequired[Decimal]
  """Total funding discount."""


class AccountMarketUpdate(TypedDict):
  """One `account_market` frame."""

  type: Literal['subscribed/account_market', 'update/account_market']
  """`subscribed/...` for the snapshot sent on subscribe, `update/...` for every later push."""
  channel: str
  """The subscribed channel in colon form (`account_market:4095:476`)."""
  account: int
  """Account index."""
  orders: list[Order]
  """Orders that changed (all open ones in the snapshot)."""
  trades: list[Trade]
  """New trades."""
  position: AccountPosition | EmptyAccountPosition | None
  """The position on this market, including an uninitialized entry with sign zero; null on frames that do not change it."""
  assets: dict[str, AccountAsset] | None
  """Spot balances by asset id (spot markets); `null` in the snapshot, `{}` on perp-market updates."""
  funding_history: list[PositionFunding] | None
  """Funding payments (perp markets); `null` in the snapshot, otherwise normally `[]`."""


class AccountMarket(StreamEndpoint):
  """Stream an account's orders, position, trades and funding (perp) or balances (spot) on one market."""

  def account_market(
    self,
    *,
    market_id: int,
    account_index: int,
    validate: bool | None = None,
  ) -> StreamManager[AccountMarketUpdate, Any, Any]:
    """Stream an account's orders, position, trades and funding (perp) or balances (spot) on one market.

    Args:
      market_id: Market id (perp or spot, per the channel).
      account_index: Account index to follow.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://apidocs.lighter.xyz/docs/websocket-reference#account-market)
    """
    return self.subscribe(
      f'account_market/{market_id}/{account_index}',
      meta={'auth': 'token'},
      validate=validate,
      response_type=AccountMarketUpdate,
    )
