# Generated by typed-dev — see CONTRIBUTING.md.
"""Shapes shared by several endpoints of this client."""

from typing_extensions import Literal, TypedDict


class ExchangeError(TypedDict):
  """An exchange action the venue refused as a whole, per Hyperliquid's `{status, response}` envelope: `status` is `err` and `response` is the rejection message."""

  status: Literal['err']
  """The venue rejected the action as a whole (e.g. an unrecognized signer)."""
  response: str
  """The venue's rejection message, e.g. 'User or API Wallet <address> does not exist.'."""
